--APAGAR DADOS DA TABELA
DELETE FROM TB_EQUIPAMENTO;
/*
RESEED: VOLTA O VALOR PARA (0)
DBCC: DATABASE CONSOLE COMANDS 
CHECKIDENT: COMANDO DBCC QUE VERIFICA/AJUSTA O VALOR DO ID
*/
DBCC CHECKIDENT ('TB_EQUIPAMENTO', RESEED, 0);
